# Esercizio 1 — Fondamenti di NumPy

**Obiettivo:** comprendere la struttura e le principali operazioni sugli array NumPy.  
Questo notebook introduce la creazione, l'indicizzazione, lo slicing e le operazioni matematiche di base.


### Vantaggi degli array NumPy rispetto alle liste Python

| Aspetto | Liste Python | Array NumPy |
|----------|---------------|-------------|
| **Tipo di dati** | Possono contenere tipi diversi | Tutti dello stesso tipo (più efficienti) |
| **Velocità** | Operazioni lente (interprete Python) | Operazioni vettoriali in C (molto più veloci) |
| **Memoria** | Struttura flessibile ma pesante | Struttura compatta e ottimizzata |
| **Operazioni matematiche** | Richiedono cicli `for` | Operano su interi array senza cicli |
| **Funzionalità avanzate** | Limitate | Broadcasting, funzioni statistiche, slicing avanzato |

➡️ **In sintesi:** gli array NumPy sono più veloci, leggeri e pratici per l’elaborazione numerica e scientifica.


In [2]:
#importare la libreria
import numpy as np
print("Libreria NumPy caricata correttamente!")

Libreria NumPy caricata correttamente!


In [4]:
#Creazione degli array numpy
# Array 1D (monodimensionale)
a = np.array([1, 2, 3, 4, 5])
print("Array a:", a)

# Array 2D (matrice)
b = np.array([[1, 2, 3], [4, 5, 6]])
print("\nArray b:\n", b)

# Array di zeri, uno e numeri casuali
zeros = np.zeros((2,3))
ones = np.ones((2,3))
randoms = np.random.randint(0, 10, (2,3))

print("\nArray di zeri:\n", zeros)
print("\nArray di uno:\n", ones)
print("\nArray casuale:\n", randoms)


Array a: [1 2 3 4 5]

Array b:
 [[1 2 3]
 [4 5 6]]

Array di zeri:
 [[0. 0. 0.]
 [0. 0. 0.]]

Array di uno:
 [[1. 1. 1.]
 [1. 1. 1.]]

Array casuale:
 [[0 9 8]
 [1 6 5]]


In [5]:
#Attributi principali di un array
print("Forma di b:", b.shape)
print("Dimensioni:", b.ndim)
print("Tipo di dato:", b.dtype)
print("Numero di elementi:", b.size)


Forma di b: (2, 3)
Dimensioni: 2
Tipo di dato: int64
Numero di elementi: 6


In [6]:
#Indicizzazione e slicing

print("Elemento b[0, 1]:", b[0, 1])
print("Prima riga di b:", b[0])
print("Seconda colonna di b:", b[:, 1])
print("Sottosezione di b:\n", b[0:2, 1:3])


Elemento b[0, 1]: 2
Prima riga di b: [1 2 3]
Seconda colonna di b: [2 5]
Sottosezione di b:
 [[2 3]
 [5 6]]


In [7]:
#Operazioni matematiche
x = np.array([10, 20, 30, 40])
y = np.array([1, 2, 3, 4])

print("Somma:", x + y)
print("Differenza:", x - y)
print("Moltiplicazione:", x * y)
print("Divisione:", x / y)
print("Quadrato:", np.square(x))
print("Radice:", np.sqrt(x))


Somma: [11 22 33 44]
Differenza: [ 9 18 27 36]
Moltiplicazione: [ 10  40  90 160]
Divisione: [10. 10. 10. 10.]
Quadrato: [ 100  400  900 1600]
Radice: [3.16227766 4.47213595 5.47722558 6.32455532]


In [10]:
#Funzioni statistiche
print("Media di x:", np.mean(x))
print("Varianza di x:", np.var(x))
print(f"Deviazione standard: {np.std(x):.2f}")
print("Massimo:", np.max(x))
print("Minimo:", np.min(x))
print("Somma totale:", np.sum(x))


Media di x: 25.0
Varianza di x: 125.0
Deviazione standard: 11.18
Massimo: 40
Minimo: 10
Somma totale: 100


In [11]:
#BROADCASTING
# Broadcasting: operazioni tra array di forme diverse
matrice = np.array([[1,2,3], [4,5,6], [7,8,9]])
vettore = np.array([10, 20, 30])

risultato = matrice + vettore
print("Matrice originale:\n", matrice)
print("Vettore:\n", vettore)
print("Risultato dopo broadcasting:\n", risultato)


Matrice originale:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Vettore:
 [10 20 30]
Risultato dopo broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


In [15]:
#Facciamo un breve esempio di normalizzazione di un vettore
valori = np.random.randint(0,10,100)
print("Valori originali:", valori)

valori_norm = (valori - np.mean(valori))/ np.std(valori)
print("Valori normalizzati (0-3):", valori_norm)

Valori originali: [1 6 4 5 8 8 7 4 7 6 1 6 7 0 3 7 2 1 5 5 1 9 3 2 5 1 2 7 9 6 2 9 7 4 0 9 8
 8 5 2 3 7 6 4 7 0 5 7 4 7 7 6 5 5 7 8 8 8 7 6 6 6 9 1 1 0 1 4 2 2 8 0 8 1
 7 9 3 3 5 7 8 0 0 4 3 6 0 4 3 4 0 4 9 7 8 9 8 8 0 3]
Valori normalizzati (0-3): [-1.33189931  0.42059978 -0.28039985  0.07009996  1.12159942  1.12159942
  0.7710996  -0.28039985  0.7710996   0.42059978 -1.33189931  0.42059978
  0.7710996  -1.68239913 -0.63089967  0.7710996  -0.98139949 -1.33189931
  0.07009996  0.07009996 -1.33189931  1.47209924 -0.63089967 -0.98139949
  0.07009996 -1.33189931 -0.98139949  0.7710996   1.47209924  0.42059978
 -0.98139949  1.47209924  0.7710996  -0.28039985 -1.68239913  1.47209924
  1.12159942  1.12159942  0.07009996 -0.98139949 -0.63089967  0.7710996
  0.42059978 -0.28039985  0.7710996  -1.68239913  0.07009996  0.7710996
 -0.28039985  0.7710996   0.7710996   0.42059978  0.07009996  0.07009996
  0.7710996   1.12159942  1.12159942  1.12159942  0.7710996   0.42059978
  0.42059978  0.4205997

### Conclusione
In questo notebook abbiamo imparato:
- la creazione e manipolazione di array NumPy (1D e 2D),
- le operazioni matematiche e statistiche più comuni,
- il concetto di *broadcasting*,
- una prima applicazione di normalizzazione dei dati.

Questo rappresenta la base per passare al prossimo notebook dedicato al *Data Preprocessing*.
