In [1]:
import numpy as np

# Creiamo una matrice A (3 documenti, 2 parole)
A = np.array([[1, 2], 
              [2, 1], 
              [10, 8]]) # Il terzo documento è molto diverso

# Applichiamo la SVD
U, s, VT = np.linalg.svd(A)

# S è restituito come un vettore per efficienza, lo trasformiamo in matrice diagonale
Sigma = np.zeros(A.shape)
np.fill_diagonal(Sigma, s)

print("Matrice U (Relazione Documenti-Concetti):\n", U)
print("\nValori Singolari (Importanza):\n", s)
print("\nMatrice VT (Relazione Parole-Concetti/Vettori Base):\n", VT)

# Verifica: U * Sigma * VT deve ridare A
A_ricostruita = U @ Sigma @ VT
print("\nMatrice Ricostruita:\n", A_ricostruita)

Matrice U (Relazione Documenti-Concetti):
 [[-0.15476143  0.8863254  -0.43643578]
 [-0.16609187 -0.4588123  -0.87287156]
 [-0.97389034 -0.06259842  0.21821789]]

Valori Singolari (Importanza):
 [13.14940783  1.04550161]

Matrice VT (Relazione Parole-Concetti/Vettori Base):
 [[-0.77766609 -0.62867755]
 [-0.62867755  0.77766609]]

Matrice Ricostruita:
 [[ 1.  2.]
 [ 2.  1.]
 [10.  8.]]
